apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: che-tls
spec:
  commonName: {{ .Values.commonName | quote }}
  dnsNames:
  - {{ .Values.commonName | quote }}
  - "*.{{- .Values.commonName | quote }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: che-tls
